spring:
  application:
    name: hystrix-turbine-server
server:
  port: 9005
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
turbine:
  aggregator:
    cluster-config: default
  app-config: say-hello-service
  cluster-name-expression: new String("default")