spring:
  application:
    name: zuul-server
  main:
    allow-bean-definition-overriding: true
server:
  port: 9020
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    say-hello:
      path: /sayHello/**
      serviceId: say-hello-service
    greeting:
      path: /greeting/**
      serviceId: greeting-service

