spring:
  application:
    name: greeting-service
  zipkin:
    base-url: http://localhost:9411
server:
  port: 9010
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能
management:
  endpoints:
    web:
      exposure:
        include: "*"