spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/rogercw/spring-cloud-config/
          username: rogercw
          password: lzy1324296138
server:
  port: 9030
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/